query ($userId: Int, $page: Int, $perPage: Int, $status: MediaListStatus) {
  Page (page: $page, perPage: $perPage) {
    mediaList (userId: $userId, status: $status, type: ANIME) {
    	media {
            title {
                userPreferred
            }
    	}
  	}
  }
}