query {
    Viewer {
        id
        name
        avatar {
            medium
        }
        statistics {
            anime {
                count
                meanScore
                standardDeviation
                minutesWatched
                episodesWatched
            }
        }
    }
}