/* tslint:disable */
/* eslint-disable */
import { GraphQLResolveInfo } from 'graphql';
/**
 * This file is auto-generated by graphql-schema-typescript
 * Please note that any changes in this file may be overwritten
 */
 

/*******************************
 *                             *
 *          TYPE DEFS          *
 *                             *
 *******************************/
export interface GQLQuery {
  Viewer?: GQLUser;
  Page?: GQLPage;
}

export interface GQLUser {
  id: number;
  name: string;
  avatar?: GQLUserAvatar;
}

export interface GQLUserAvatar {
  large?: string;
  medium?: string;
}

export interface GQLPage {
  mediaList?: Array<GQLMediaList | null>;
}

export interface GQLMediaList {
  media?: GQLMedia;
}

export interface GQLMedia {
  title?: GQLMediaTitle;
}

export interface GQLMediaTitle {
  userPreferred?: string;
}

export enum GQLMediaListStatus {
  CURRENT = 'CURRENT',
  PLANNING = 'PLANNING',
  COMPLETED = 'COMPLETED',
  DROPPED = 'DROPPED',
  PAUSED = 'PAUSED',
  REPEATING = 'REPEATING'
}

/*********************************
 *                               *
 *         TYPE RESOLVERS        *
 *                               *
 *********************************/
/**
 * This interface define the shape of your resolver
 * Note that this type is designed to be compatible with graphql-tools resolvers
 * However, you can still use other generated interfaces to make your resolver type-safed
 */
export interface GQLResolver {
  Query?: GQLQueryTypeResolver;
  User?: GQLUserTypeResolver;
  UserAvatar?: GQLUserAvatarTypeResolver;
  Page?: GQLPageTypeResolver;
  MediaList?: GQLMediaListTypeResolver;
  Media?: GQLMediaTypeResolver;
  MediaTitle?: GQLMediaTitleTypeResolver;
}
export interface GQLQueryTypeResolver<TParent = any> {
  Viewer?: QueryToViewerResolver<TParent>;
  Page?: QueryToPageResolver<TParent>;
}

export interface QueryToViewerResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface QueryToPageResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLUserTypeResolver<TParent = any> {
  id?: UserToIdResolver<TParent>;
  name?: UserToNameResolver<TParent>;
  avatar?: UserToAvatarResolver<TParent>;
}

export interface UserToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface UserToNameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface UserToAvatarResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLUserAvatarTypeResolver<TParent = any> {
  large?: UserAvatarToLargeResolver<TParent>;
  medium?: UserAvatarToMediumResolver<TParent>;
}

export interface UserAvatarToLargeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface UserAvatarToMediumResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLPageTypeResolver<TParent = any> {
  mediaList?: PageToMediaListResolver<TParent>;
}

export interface PageToMediaListResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLMediaListTypeResolver<TParent = any> {
  media?: MediaListToMediaResolver<TParent>;
}

export interface MediaListToMediaResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLMediaTypeResolver<TParent = any> {
  title?: MediaToTitleResolver<TParent>;
}

export interface MediaToTitleResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLMediaTitleTypeResolver<TParent = any> {
  userPreferred?: MediaTitleToUserPreferredResolver<TParent>;
}

export interface MediaTitleToUserPreferredResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}
